# .github/workflows/passive-tree-etl.yml

name: Passive Tree & Boss ETL

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  schedule:
    # daily at 02:00 UTC
    - cron:  '0 2 * * *'

jobs:
  etl:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Initialize database schema
        run: python scripts/setup_db.py

      - name: Apply boss table migrations
        run: python migrations/migrate_add_boss_tables.py

      # Passive Tree ETL
      - name: Fetch & Load Passive Tree
        run: python scripts/fetch_and_load_tree401.py

      - name: Load Passive Tree into DB
        run: python scripts/load_tree401.py

      # Ascendancy ETL
      - name: Fetch & Load Ascendancy Data
        run: python scripts/fetch_ascendancy_data.py

      - name: Load Ascendancy into DB
        run: python scripts/load_ascendancy.py

      # Item ETL
      - name: Fetch PoB Item Data
        run: python scripts/fetch_pob_data.py

      - name: Load Items into DB
        run: python scripts/load_items.py

      # Boss ETL
      - name: Fetch Boss Data
        run: python scripts/fetch_pob_boss_data.py

      - name: Load Boss ETL
        run: python scripts/load_bosses.py

      # Smoke Tests
      - name: Run Passive ETL Smoke Tests
        run: pytest tests/test_smoke_etl.py

      - name: Run Ascendancy ETL Smoke Tests
        run: pytest tests/test_smoke_ascendancy_etl.py

      - name: Run Item ETL Smoke Tests
        run: pytest tests/test_smoke_items_etl.py

      - name: Run Boss ETL Smoke Tests
        run: pytest tests/test_smoke_boss_etl.py
