name: Passive Tree ETL

on:
  schedule:
    - cron: '0 2 * * *'    # daily at 02:00 UTC
  workflow_dispatch:
  push:
    paths:
      - 'requirements.txt'
      - 'scripts/**'
      - 'data/**'
      - 'tests/**'
      - '.github/workflows/passive-tree-etl.yml'
  pull_request:
    paths:
      - 'scripts/**'
      - 'data/**'
      - 'tests/**'

permissions:
  contents: write
  actions: read

jobs:
  etl:
    name: Full ETL & Smoke‑Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch tree401.json
        id: fetch
        run: |
          mkdir -p data/raw_trees db
          RAW_PATH=$(python scripts/FetchAndLoadTree401.py)
          BASENAME=$(basename "$RAW_PATH")
          TIMESTAMP=${BASENAME%.json}
          echo "raw_path=$RAW_PATH"    >> $GITHUB_OUTPUT
          echo "timestamp=$TIMESTAMP"  >> $GITHUB_OUTPUT

      - name: Register version in DB
        id: register
        env:
          DB_URL: ${{ secrets.DB_URL }}
        run: |
          python scripts/register_tree_version.py \
            --json-file "${{ steps.fetch.outputs.raw_path }}" \
            --timestamp "${{ steps.fetch.outputs.timestamp }}" \
            --return-version-id > version_id.txt
          echo "version_id=$(cat version_id.txt)" >> $GITHUB_OUTPUT

      - name: Load passive tree into SQLite
        env:
          VERSION_ID: ${{ steps.register.outputs.version_id }}
          RAW_PATH:    ${{ steps.fetch.outputs.raw_path }}
        run: |
          python scripts/load_tree401.py \
            --json-file "$RAW_PATH" \
            --version-id $VERSION_ID

      - name: Run smoke tests
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Commit raw JSON snapshot
        if: always()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f data/raw_trees/${{ steps.fetch.outputs.timestamp }}.json
          git commit -m "chore: fetch tree401.json version ${{ steps.fetch.outputs.timestamp }}" || echo "no changes to commit"
          git push

