name: MCP ETL Pipeline

on:
  schedule:
    - cron: '0 2 * * *'     # daily at 02:00 UTC
  workflow_dispatch:
  push:
    paths:
      - 'requirements.txt'
      - 'scripts/**'
      - 'data/**'
      - 'tests/**'
      - '.github/workflows/passive-tree-etl.yml'
  pull_request:
    paths:
      - 'scripts/**'
      - 'data/**'
      - 'tests/**'

jobs:
  tree-etl:
    name: Passive‑Tree ETL
    runs-on: ubuntu-latest
    outputs:
      version_id: ${{ steps.register_tree.outputs.VERSION_ID }}
      raw_path:    ${{ steps.fetch_tree.outputs.RAW_PATH }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare database
        run: |
          mkdir -p db
          python scripts/setup_db.py
        # Export DB_URL so SQLAlchemy can open it
      - name: Export DB_URL
        run: echo "DB_URL=sqlite://${{ github.workspace }}/db/passive_tree.db" >> $GITHUB_ENV

      - name: Fetch & snapshot tree401.json
        id: fetch_tree
        run: |
          mkdir -p data/raw_trees
          raw_path=$(python scripts/FetchAndLoadTree401.py)
          echo "RAW_PATH=$raw_path" >> $GITHUB_OUTPUT

      - name: Register version in DB
        id: register_tree
        run: |
          VERSION_ID=$(python scripts/register_tree_version.py \
            --json-file "${{ steps.fetch_tree.outputs.RAW_PATH }}" \
            --timestamp "$(basename "${{ steps.fetch_tree.outputs.RAW_PATH }}" .json)" \
            --return-version-id)
          echo "VERSION_ID=$VERSION_ID" >> $GITHUB_OUTPUT

      - name: Migrate passive‑tree extras
        run: python scripts/migrate_add_error_and_starting_tables.py || true

      - name: Load passive tree & run smoke‑tests
        env:
          RAW_PATH:   ${{ steps.fetch_tree.outputs.RAW_PATH }}
          VERSION_ID: ${{ steps.register_tree.outputs.VERSION_ID }}
        run: |
          python scripts/load_tree401.py \
            --json-file "$RAW_PATH" \
            --version-id $VERSION_ID
          pytest tests/test_smoke_etl.py -q

  item-etl:
    name: Item ETL
    needs: tree-etl
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare database
        run: |
          mkdir -p db
          python scripts/setup_db.py
      - name: Export DB_URL
        run: echo "DB_URL=sqlite://${{ github.workspace }}/db/passive_tree.db" >> $GITHUB_ENV

      - name: Fetch PoB data
        run: python scripts/fetch_pob_data.py

      - name: Load items & run smoke‑tests
        run: |
          python scripts/load_items.py
          pytest tests/test_smoke_items_etl.py -q
