name: Passive Tree & Boss ETL

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  schedule:
    - cron: '0 2 * * *'  # daily at 02:00 UTC

jobs:
  etl:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Initialize database schema
        run: python scripts/setup_db.py

      - name: Seed boss‑skill overrides
        run: sqlite3 db/passive_tree.db < migrations/005_seed_skill_to_boss.sql

      # Passive Tree ETL
      - name: Fetch passive‑tree JSON
        run: python scripts/FetchAndLoadTree401.py

      - name: Register tree version
        run: |
          ver=$(python scripts/register_tree_version.py --json-file data/tree401.json)
          echo "VERSION=$ver" >> $GITHUB_ENV

      - name: Load passive tree into DB
        run: python scripts/load_tree401.py --json-file data/tree401.json --version-id ${{ env.VERSION }}

      # Item ETL
      - name: Fetch PoB item data
        run: python scripts/fetch_pob_data.py

      - name: Load items into DB
        run: python scripts/load_items.py

      # Boss ETL
      - name: Fetch boss data
        run: python scripts/fetch_pob_boss_data.py

      - name: Load bosses into DB
        run: python scripts/load_bosses.py

      # Smoke Tests
      - name: Run Passive ETL Smoke Tests
        run: pytest tests/test_smoke_etl.py

      - name: Run Item ETL Smoke Tests
        run: pytest tests/test_smoke_items_etl.py

      - name: Run Boss ETL Smoke Tests
        run: pytest tests/test_smoke_boss_etl.py

