name: Passive Tree ETL

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  push:
    paths:
      - 'requirements.txt'
      - 'scripts/**'
      - 'data/**'
      - 'tests/**'
      - '.github/workflows/passive-tree-etl.yml'
  pull_request:
    paths:
      - 'scripts/**'
      - 'data/**'
      - 'tests/**'

permissions:
  contents: write
  actions: read

jobs:
  fetch-and-register:
    name: Fetch & Register Version
    runs-on: ubuntu-latest
    outputs:
      version_id: ${{ steps.register.outputs.version_id }}
      raw_path:    ${{ steps.fetch.outputs.raw_path }}
      timestamp:   ${{ steps.fetch.outputs.timestamp }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch tree401.json snapshot
        id: fetch
        run: |
          mkdir -p data/raw_trees
          RAW_OUTPUT=$(python scripts/FetchAndLoadTree401.py)
          RAW_PATH=$(echo "$RAW_OUTPUT" | tail -n1)
          BASENAME=$(basename "$RAW_PATH")
          TIMESTAMP=${BASENAME%.json}
          echo "raw_path=$RAW_PATH"    >> $GITHUB_OUTPUT
          echo "timestamp=$TIMESTAMP"  >> $GITHUB_OUTPUT
          echo "$RAW_OUTPUT"

      - name: List raw_trees directory
        run: ls -l data/raw_trees

      - name: Ensure db directory exists
        run: mkdir -p db

      - name: Register version in DB
        id: register
        env:
          DB_URL: ${{ secrets.DB_URL }}
        run: |
          python scripts/register_tree_version.py \
            --json-file "${{ steps.fetch.outputs.raw_path }}" \
            --timestamp "${{ steps.fetch.outputs.timestamp }}" \
            --return-version-id > version_id.txt
          VERSION_ID=$(cat version_id.txt)
          echo "version_id=$VERSION_ID" >> $GITHUB_OUTPUT

      - name: Commit raw JSON snapshot
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f "data/raw_trees/${{ steps.fetch.outputs.timestamp }}.json"
          git commit -m "chore: fetch tree401.json version ${{ steps.fetch.outputs.timestamp }}"
          git push

  load-and-test:
    name: Load Tree & Smoke‑Test
    needs: fetch-and-register
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure db directory exists
        run: mkdir -p db

      - name: Initialize SQLite schema
        run: python scripts/setup_db.py

      - name: Apply schema migrations
        run: python scripts/migrate_add_error_and_starting_tables.py

      - name: Load passive tree into SQLite
        env:
          VERSION_ID: ${{ needs.fetch-and-register.outputs.version_id }}
          RAW_PATH:    ${{ needs.fetch-and-register.outputs.raw_path }}
        run: |
          python scripts/load_tree401.py \
            --json-file "$RAW_PATH" \
            --version-id $VERSION_ID

      - name: Run smoke tests
        run: pytest --maxfail=1 --disable-warnings -q
